
server:
  port: 9001

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:

      ddl-auto: update

    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/db_login?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: nhanbn98
google:
  clientId: 569599946060-n9jf1jqt006ts166fl4gttnjpb80e4i1.apps.googleusercontent.com

jwt:
  secret: kjfhaskjhfdsljhfdsljhfdsklhfdsllj
  expiration: 3600000

secretPsw: kaslfdhyliudfshiuywrdhwlerawel

